
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 30 14:53:05 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 12;
  public static final int IDENT = 26;
  public static final int PERCENT = 25;
  public static final int DOTCOMMA = 11;
  public static final int PLUS = 21;
  public static final int RBRACE = 5;
  public static final int RPAREN = 14;
  public static final int EQUAL = 8;
  public static final int RETURN = 3;
  public static final int MINUSMINUS = 10;
  public static final int LPAREN = 13;
  public static final int LBRACE = 6;
  public static final int COMMA = 16;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int CHARCONST = 4;
  public static final int DIV = 24;
  public static final int PROG = 2;
  public static final int MINUS = 22;
  public static final int LSQUARE = 19;
  public static final int PLUSPLUS = 9;
  public static final int CONST = 7;
  public static final int PRINT = 15;
  public static final int error = 1;
  public static final int RSQUARE = 20;
  public static final int NEW = 18;
  public static final int MUL = 23;
  public static final int BOOLCONST = 17;
}

