
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 21 12:08:32 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 11;
  public static final int IDENT = 24;
  public static final int PERCENT = 23;
  public static final int DOTCOMMA = 10;
  public static final int PLUS = 19;
  public static final int RBRACE = 4;
  public static final int RPAREN = 13;
  public static final int EQUAL = 7;
  public static final int RETURN = 3;
  public static final int MINUSMINUS = 9;
  public static final int LPAREN = 12;
  public static final int LBRACE = 5;
  public static final int COMMA = 15;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int CHARCONST = 27;
  public static final int DIV = 22;
  public static final int PROG = 2;
  public static final int MINUS = 20;
  public static final int LSQUARE = 17;
  public static final int PLUSPLUS = 8;
  public static final int CONST = 6;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int RSQUARE = 18;
  public static final int NEW = 16;
  public static final int MUL = 21;
  public static final int BOOLCONST = 26;
}

