
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 25 19:21:43 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 13;
  public static final int IDENT = 28;
  public static final int PERCENT = 27;
  public static final int DOTCOMMA = 12;
  public static final int PLUS = 23;
  public static final int RBRACE = 6;
  public static final int RPAREN = 15;
  public static final int EQUAL = 9;
  public static final int RETURN = 3;
  public static final int MINUSMINUS = 11;
  public static final int LPAREN = 14;
  public static final int LBRACE = 7;
  public static final int COMMA = 17;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int CHARCONST = 5;
  public static final int DIV = 26;
  public static final int PROG = 2;
  public static final int MINUS = 24;
  public static final int LSQUARE = 21;
  public static final int PLUSPLUS = 10;
  public static final int CONST = 8;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int RSQUARE = 22;
  public static final int NEW = 20;
  public static final int MUL = 25;
  public static final int VOID = 4;
  public static final int BOOLCONST = 19;
}

